<a href="https://colab.research.google.com/github/KrisrcQi/Crsp_mutual_fund_matrix_completion/blob/main/Test_of_matrix_NAV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


# Reading the data file
# Checking the empty cells in the dataset
df = pd.read_csv('Downsized dataset(10k row).csv')
print(df)
small_date = df['caldt'].min()
print(small_date)
max_date = df['caldt'].max()
print(max_date)



      Unnamed: 0       caldt  crsp_fundno  mtna     mnav
0              0  28/06/2019        95598   0.1  10.0100
1              1  31/07/2019        95598   0.1  10.0100
2              2  30/08/2019        95598   0.1  10.0200
3              3  30/09/2019        95598   0.1  10.0200
4              4  31/10/2019        95598   0.1  10.0200
...          ...         ...          ...   ...      ...
9980        9980  30/04/2020        96709   2.3  10.8100
9981        9981  31/03/2020        96710   0.1  10.0000
9982        9982  30/04/2020        96710   0.1  10.8100
9983        9983  31/03/2020        96711   4.0  40.0000
9984        9984  30/04/2020        96711  13.8  44.3728

[9985 rows x 5 columns]
26/02/2010
31/12/2019


In [ ]:
df_1 = df[: 633]
df_1 = df.drop(['caldt'], axis=1)
df_1

Unnamed: 0  crsp_fundno  mtna     mnav
0              0        95598   0.1  10.0100
1              1        95598   0.1  10.0100
2              2        95598   0.1  10.0200
3              3        95598   0.1  10.0200
4              4        95598   0.1  10.0200
...          ...          ...   ...      ...
9980        9980        96709   2.3  10.8100
9981        9981        96710   0.1  10.0000
9982        9982        96710   0.1  10.8100
9983        9983        96711   4.0  40.0000
9984        9984        96711  13.8  44.3728

[9985 rows x 4 columns]

In [ ]:
print(type(first_column))
print(first_column)

# Convert object-type column to float
df_1['caldt'] = df_1['caldt'].astype(str)

first_column = df_1.iloc[:, 1]
# Verify the conversion
print(first_column)

<class 'pandas.core.series.Series'>
0      28/06/2019
1      31/07/2019
2      30/08/2019
3      30/09/2019
4      31/10/2019
          ...    
628    31/03/2020
629    30/04/2020
630    31/07/2019
631    30/08/2019
632    30/09/2019
Name: caldt, Length: 633, dtype: object
0      28/06/2019
1      31/07/2019
2      30/08/2019
3      30/09/2019
4      31/10/2019
          ...    
628    31/03/2020
629    30/04/2020
630    31/07/2019
631    30/08/2019
632    30/09/2019
Name: caldt, Length: 633, dtype: object


<ipython-input-50-bb0a17d836f9>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['caldt'] = df_1['caldt'].astype(str)


In [ ]:
print(type(second_column))
print(second_column)

<class 'pandas.core.series.Series'>
0      95598.0
1      95598.0
2      95598.0
3      95598.0
4      95598.0
        ...   
628    95638.0
629    95638.0
630    95639.0
631    95639.0
632    95639.0
Name: crsp_fundno, Length: 633, dtype: float64


In [ ]:

mf_id = list(range(95598, 95608))
# Create an empty DataFrame
# Create a date range from '2008-07' to '2020-04'
date_range = pd.date_range('2008-07', '2020-04', freq='M')

# Create a new DataFrame with the 'date' column
df_2 = pd.DataFrame({'date': date_range})

# Convert the 'date' column to string datatype
df_2['date'] = df_2['date'].dt.strftime('%Y-%m')

column_names = [i for i in range(95598, 95608)]
df_2 = pd.concat([df_2, pd.DataFrame(columns=column_names)], ignore_index=True)

print(df_2)

        date 95598 95599 95600 95601 95602 95603 95604 95605 95606 95607
0    2008-07   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1    2008-08   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2    2008-09   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3    2008-10   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4    2008-11   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
..       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
136  2019-11   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
137  2019-12   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
138  2020-01   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
139  2020-02   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
140  2020-03   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[141 rows x 11 columns]


In [ ]:
for i in range(len(mf_id)):
  print(i)
  for j in range(len(df_1)):
    for k in range(len(df_2)):
      if (df_1.iloc[j]['crsp_fundno']) == mf_id[i]:
        if(df_1.iloc[j]['caldt']) == df_2.iloc[k]['date']:
          df_2.iloc[k, i+1] = df_1.iloc[j]['mnav']

print(df_2)
df_2.to_csv('Matrix_NAV.csv')


0
1
2
3
4
5
6
7
8
9
        date 95598 95599 95600 95601 95602 95603 95604 95605 95606 95607
0    2008-07   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1    2008-08   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2    2008-09   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3    2008-10   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4    2008-11   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
..       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
136  2019-11   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
137  2019-12   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
138  2020-01   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
139  2020-02   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
140  2020-03   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[141 rows x 11 columns]


In [ ]:
!pip install torch-geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.6/661.6 kB 11.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for torch-geometric: filename=torch_geometric-2.3.1-py3-none-any.whl size=910459 sha256=3445bb49895e4a89aff3a93b6774b194080a8de877b4bf92c35b0aaf345ff0f9
  Stored in directory: /root/.cache/pip/wheels/ac/dc/30/e2874821ff308ee67dcd7a66dbde912411e19e35a1addda028
Successfully built torch-geometric


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv

data = df_1
num_features = 10

# Step 1: Convert matrix to graph representation
adjacency_matrix = torch.tensor(data.values)  # Convert matrix to tensor
edge_index = adjacency_matrix.nonzero().t()  # Get indices of non-zero values as edges
x = torch.randn(adjacency_matrix.size(0), num_features)  # Node features (randomly initialized)


In [ ]:
adjacency_matrix


tensor([[0.00e+00, 9.56e+04, 1.00e-01, 1.00e+01],
        [1.00e+00, 9.56e+04, 1.00e-01, 1.00e+01],
        [2.00e+00, 9.56e+04, 1.00e-01, 1.00e+01],
        ...,
        [9.98e+03, 9.67e+04, 1.00e-01, 1.08e+01],
        [9.98e+03, 9.67e+04, 4.00e+00, 4.00e+01],
        [9.98e+03, 9.67e+04, 1.38e+01, 4.44e+01]], dtype=torch.float64)

In [ ]:
edge_index

tensor([[   0,    0,    0,  ..., 9984, 9984, 9984],
        [   1,    2,    3,  ...,    1,    2,    3]])

In [ ]:
x

tensor([[-0.75, -0.21, -0.05,  ..., -2.18,  0.40, -0.68],
        [-1.45,  0.91, -0.21,  ...,  0.46,  0.27,  0.35],
        [-1.86, -1.65,  1.20,  ...,  0.15, -0.57, -1.19],
        ...,
        [ 1.43,  1.13, -0.54,  ...,  0.64, -0.90, -0.68],
        [-2.75,  0.51, -0.04,  ...,  0.34,  1.37, -2.48],
        [ 1.37,  0.54, -0.23,  ...,  0.40,  0.49,  1.71]])

In [ ]:
# Step 2: Split the dataset
# Randomly remove some values to create observed values dataset
observed_matrix = adjacency_matrix.clone()
indices = torch.randperm(adjacency_matrix.numel())[:int(0.8 * adjacency_matrix.numel())]
observed_matrix.reshape(-1)[indices] = float('nan')
# Keep missing values as the evaluation dataset
missing_values = adjacency_matrix.clone()
missing_values.reshape(-1)[indices] = float('nan')

In [ ]:
# Step 3: Construct the GNN model
class GNNModel(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super(GNNModel, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, 1)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = F.relu(self.conv2(x, edge_index))
        x = self.fc(x).squeeze()
        return x

input_dim = num_features  # Dimensionality of input features
hidden_dim = 64  # Dimensionality of hidden layers

model = GNNModel(input_dim, hidden_dim)

In [ ]:
# Step 4: Train the GNN model
criterion = nn.MSELoss()  # Mean Squared Error loss
optimizer = optim.Adam(model.parameters(), lr=0.01)

data = Data(x=x, edge_index=edge_index)
loader = DataLoader([data], batch_size=64)  # DataLoader for a single graph

num_epochs = 40

# Training loop
for epoch in range(num_epochs):
    model.train()
    for batch in loader:
        optimizer.zero_grad()
        output = model(batch.x, batch.edge_index)
        target = batch.x.t()  # Transpose the target tensor to match output shape
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        print('Epoch[{}/{}], loss:{:,6f}'.format(i, num_epochs, loss.data))

/usr/local/lib/python3.10/dist-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([10, 9985])) that is different to the input size (torch.Size([9985])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [ ]:
# Step 5: Evaluate the GNN model
model.eval()
with torch.no_grad():
    missing_values_prediction = model(x, edge_index)  # Predict missing values


# Convert the predicted missing values back to a matrix
predicted_matrix = adjacency_matrix.clone().double()  # Convert predicted_matrix to Double data type
selected_indices = indices[:missing_values_prediction.size(0)]
predicted_matrix.reshape(-1)[selected_indices] = missing_values_prediction.double()  # Convert missing_values_prediction to Double data type



In [ ]:
# Print the predicted matrix
torch.set_printoptions(precision=2)
print(predicted_matrix)

tensor([[0.00e+00, 9.56e+04, 1.00e-01, 1.00e+01],
        [1.00e+00, 9.56e+04, 1.00e-01, 1.00e+01],
        [2.00e+00, 9.56e+04, 1.00e-01, 1.00e+01],
        ...,
        [9.98e+03, 9.67e+04, 1.00e-01, 1.08e+01],
        [9.98e+03, 9.67e+04, 4.00e+00, 4.00e+01],
        [9.98e+03, 9.67e+04, 1.38e+01, 4.44e+01]], dtype=torch.float64)


In [ ]:
# Convert the tensor to a NumPy array
predicted_array = predicted_matrix.numpy()

# Create a new DataFrame from the array
predicted_df = pd.DataFrame(predicted_array)

# Print the new DataFrame
print(predicted_df)

           0        1     2        3
0        0.0  95598.0   0.1  10.0100
1        1.0  95598.0   0.1  10.0100
2        2.0  95598.0   0.1  10.0200
3        3.0  95598.0   0.1  10.0200
4        4.0  95598.0   0.1  10.0200
...      ...      ...   ...      ...
9980  9980.0  96709.0   2.3  10.8100
9981  9981.0  96710.0   0.1  10.0000
9982  9982.0  96710.0   0.1  10.8100
9983  9983.0  96711.0   4.0  40.0000
9984  9984.0  96711.0  13.8  44.3728

[9985 rows x 4 columns]


In [ ]:
predicted_df.to_csv('predicted matrix.csv')